---
resource_types:
- name: email
  type: docker-image
  source:
    repository: mdomke/concourse-email-resource

resources:
- name: docker-file-repo
  type: git
  source:
    uri: ((dockerfile-git-uri))
    branch: master
- name: golang-image
  type: docker-image
  source: ((docker-registry-source))
- name: cli-code
  type: git
  source:
    uri: ((yml2env-git-uri))
    branch: master
- name: release-candidate
  type: s3
  source:
    endpoint: training-box-minio:9000
    disable_ssl: true
    bucket: release-candidates
    regexp: yml2env-(.*)
    access_key_id: ((access_key))
    secret_access_key: ((secret_key))
- name: test-report
  type: s3
  source:
    endpoint: training-box-minio:9000
    disable_ssl: true
    bucket: test-reports
    regexp: junit-(.*)
    access_key_id: ((access_key))
    secret_access_key: ((secret_key))
- name: send-email
  type: email
  source:
    from: ci@example.com

jobs:
- name: build-image
  plan:
  - get: docker-file-repo
    trigger: true
  - put: golang-image
    params:
      build: docker-file-repo

- name: compile
  plan:
  - get: cli-code
    trigger: true
  - get: golang-image
    passed: [build-image]
    trigger: true
  - task: lint
    image: golang-image
    file: cli-code/lint.yml
  - task: go-build
    image: golang-image
    file: cli-code/compile.yml
  - put: release-candidate
    params:
      file: built-binary/yml2env-*

- name: test
  plan:
  - get: cli-code
    passed: [compile]
    trigger: true
  - task: test
    attempts: 10
    file: cli-code/test.yml
    params:
      FIXTURE_LOCATION: fixtures/
      FLAKE: some-value
    on_failure:
      do:
      - put: send-email
        params:
          to: [concoursetraining@mailsac.com]
          subject_text: Concourse Training
          body_text: Some text
      - put: test-report
        params:
          file: test-report/junit-*.xml
