---
resources:
- name: docker-file-repo
  type: git
  source:
    uri: http://training-box-gogs/student/lab-assets
    branch: master
- name: golang-image
  type: docker-image
  source:
    repository: training-box-docker-registry:5000/student/golang-image
    insecure_registries: [ "training-box-docker-registry:5000" ]
- name: cli-code
  type: git
  source:
    uri: http://training-box-gogs/student/yml2env
    branch: master
- name: release-candidate
  type: s3
  source:
    endpoint: training-box-minio:9000
    disable_ssl: true
    bucket: release-candidates
    regexp: yml2env-(.*)
    access_key_id: "123456"
    secret_access_key: qwertyui

jobs:
- name: build-image
  plan:
  - get: docker-file-repo
  - put: golang-image
    params:
      build: docker-file-repo

- name: compile
  plan:
  - get: cli-code
  - task: go-build
    config:
      platform: linux

      # Define the Docker image to use as the filesystem for this task
      image_resource:
        type: docker-image
        source:
          repository: training-box-docker-registry:5000/student/golang-image
          insecure_registries: [ "training-box-docker-registry:5000" ]

      # Tell Concourse which things to mount into the container
      inputs:
      - name: cli-code
      outputs:
      - name: built-binary

      # Run a shell script to compile the code
      run:
        path: /bin/sh
        args:
        - -xc
        - |
          mkdir -p src/github.com/EngineerBetter/yml2env
          mv cli-code/* src/github.com/EngineerBetter/yml2env
          export GOPATH=$PWD
          cd src/github.com/EngineerBetter/yml2env
          go build -o $OLDPWD/built-binary/yml2env-$(date +%s)
  - put: release-candidate
    params:
      file: built-binary/yml2env-*

- name: test
  plan:
  - get: cli-code
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: training-box-docker-registry:5000/student/golang-image
          insecure_registries: [ "training-box-docker-registry:5000" ]
      inputs:
      - name: cli-code
        path: gopath/src/github.com/EngineerBetter/yml2env
      run:
        path: gopath/src/github.com/EngineerBetter/yml2env/test.sh
